#cloud-config
packages:
  - git
runcmd:
  - curl -fsSL https://get.docker.com | sh
  - git clone git@github.com:foodelevator/dd2482-demo-preview-deployments.git
  - cd dd2482-demo-preview && docker compose -f infra/traefik.compose.yaml up -d
