services:
  traefik:
    image: traefik:v3.5.1
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yml:ro
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    networks:
      - traefik
    restart: always

networks:
  traefik:
    driver: bridge
    name: traefik

volumes:
  data:
