services:
  test:
    labels:
      - traefik.enable=true
      - traefik.http.routers.test-${NAME}.rule=Host(`${NAME:?error}.devops-demo.0m.nu`)
      - traefik.http.routers.test-${NAME}.tls.certresolver=default
    build: .
    networks:
      - traefik

networks:
  traefik:
    external: true
