name: "Close Pull Request Preview"
on:
  pull_request:
    types: [closed]

jobs:
  close_pr_preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v5

      - name: Load SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          echo "ipv4-ssh.devops-demo.0m.nu ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDz2WeOy65+ErgkA+yvgA/8Z1Nx7+ayN7wfwtwF8vGMm" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_ed25519
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Run docker compose down
        env:
          DOCKER_HOST: ssh://user@ipv4-ssh.devops-demo.0m.nu
          PR: ${{ github.event.number }}
        run: docker compose --project-name test-preview-$PR -f app/compose.yaml down
